# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 1
  end

  config.vm.define "api" do |api|
      api.vm.network "forwarded_port", guest: 80, host: 8080
      api.vm.network "public_network", ip: "192.168.50.4"
      api.vm.synced_folder "api", "/app"
      api.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y nginx python3-pip htop supervisor || :
        pip3 install tornado redis &&

        echo "192.168.50.5  resources.io" >> /etc/hosts
        hostname "api"

        if [[ ! -h /etc/nginx/sites-enabled/api ]]; then
            ln -s /app/nginx/sites-enabled/api /etc/nginx/sites-enabled/api || :
        fi
        service nginx restart

        if [ ! -h /etc/supervisor/conf.d/api.conf ]; then
            ln -s /app/supervisor/conf.d/api.conf /etc/supervisor/conf.d/api.conf || :
        fi
        if [ ! -h /etc/supervisor/conf.d/system_monitor.conf ]; then
            ln -s /app/supervisor/conf.d/system_monitor.conf /etc/supervisor/conf.d/system_monitor.conf || :
        fi
        supervisorctl reload

      SHELL
  end

  config.vm.define "resources" do |resources|
      resources.vm.network "forwarded_port", guest: 80, host: 8081
      resources.vm.network "forwarded_port", guest: 6379, host: 63799
      resources.vm.network "public_network", ip: "192.168.50.5"
      resources.vm.synced_folder "resources", "/app"
      resources.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install -y nginx python3-pip redis-server htop supervisor || :
        pip3 install tornado redis &&
        hostname "resources"

        # Set up redis process
        rm -rf /etc/redis/redis.conf
        ln -s /app/redis/redis.conf /etc/redis/redis.conf || :
        chown root:root /app/redis/redis.conf
        chmod 655 /app/redis/redis.conf
        service redis-server restart

        # Set up supervisor processes
        if [ ! -h /etc/supervisor/conf.d/resources.conf ]; then
            ln -s /app/supervisor/conf.d/resources.conf /etc/supervisor/conf.d/resources.conf || :
        fi
        supervisorctl reload

        # Set up nginx
        if [[ ! -h /etc/nginx/sites-enabled/resources ]]; then
            ln -s /app/nginx/sites-enabled/resources /etc/nginx/sites-enabled/resources || :
        fi
        service nginx restart

      SHELL
  end

end
